baseURL: https://mduong26.github.io
languageCode: en-us
title: Michelle Duong Website
theme: toha

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

enableEmoji: true

params:
  gitRepo: https://github.com/mduong26/mduong26.github.io
  enableBlogPost: false
  enableTOC: false

  newsletter:
    enable: false

  background: "images/bg.jpg"
